### ISSUE TITLE
Extension logs errors when it can't find component

### ISSUE THREAD

**Issue by rohit-gohri** [marko-js/language-server#10]
When hovering over some attribute value or the `if` tag the extension opens the output window in VS Code and logs some errors:
```
[Error - 1:49:16 AM] Request textDocument/definition failed.
  Message: Request textDocument/definition failed with message: EISDIR: illegal operation on a directory, read
  Code: -32603 
[Error - 1:49:18 AM] Request textDocument/definition failed.
  Message: Request textDocument/definition failed with message: Couldn't match the scopeType: 3
  Code: -32603 
[Error - 1:49:19 AM] Request textDocument/definition failed.
  Message: Request textDocument/definition failed with message: Couldn't find a definition for tag: if
  Code: -32603 
```

I think #6 covered all console statements, but this `throw new Error` in https://github.com/marko-js/marko-language-server/blob/1fdedd9e1dc536d36234354f2f45a894418cabd5/server/src/service.ts#L379-L388 directly opens the output window in VS code and some other cases are throwing too. 

Seems like the only way to handle this would be add try catches everywhere as there is no global error handler: https://github.com/Microsoft/vscode/issues/45264

**Comment by DylanPiercey** [comment]
Should be fixed now!
