### ISSUE TITLE
VSCode IntelliSense does not load/work anymore

### ISSUE THREAD

**Issue by MiloCasagrande** [marko-js/language-server#155]
### Details

With version 1.0.10 of the marko VSCode extension installed, the JS/TS language service does not work anymore.

This is the error I see on VSCode:
```
The JS/TS language service immediately crashed 5 times. The service will not be restarted. This may be caused by a plugin contributed by one of these extensions: Marko-JS.marko-vscode, VisualStudioExptTeam.vscodeintellicode, VisualStudioExptTeam.vscodeintellicode.
```

And from the output console:
```
2023-04-06 09:24:26.855 [error] Error: <semantic> TypeScript Server Error (5.0.3)
Cannot read properties of undefined (reading 'resolutions')
TypeError: Cannot read properties of undefined (reading 'resolutions')
```

Downgrading to 1.0.9 the JS/TS language service works fine again.
Not sure this is something with the marko VSCode extension of with VSCode itself though.

### Your Environment

- VSCode Version: 1.77.1
- Commit: b7886d7461186a5eac768481578c1d7ca80e2d21
- Date: 2023-04-04T23:22:38.708Z
- Electron: 19.1.11
- Chromium: 102.0.5005.196
- Node.js: 16.14.2
- V8: 10.2.154.26-electron.0
- OS: Darwin arm64 22.4.0
- Sandboxed: No

**Comment by DylanPiercey** [comment]
I believe this is resolved by https://github.com/marko-js/language-server/pull/156. Feel free to ping if that's not the case.
