### ISSUE TITLE
Publish VSCode extension to Open-VSX registry

### ISSUE THREAD

**Issue by ghost** [marko-js/language-server#21]
### Description

We're using Theia as an integrated IDE which uses VSCode-compatible extensions published to [Open-VSX](https://open-vsx.org/about). Currently, the VSCode extension is not published to Open-VSX, so we do not enjoy any syntax highlighting or other DX niceties.

### Why

Publishing the VSCode extension to Open-VSX will enable improved DX in any VSX compatible IDE.

### Possible Implementation & Open Questions

https://github.com/eclipse/openvsx/wiki/Publishing-Extensions#how-to-publish-an-extension

**Comment by DylanPiercey** [comment]
I set this up to publish to open vsx almost 9 months ago but forgot to close the issue! Sorry about that.
https://open-vsx.org/extension/Marko-JS/marko-vscode
