### ISSUE TITLE
Autocomplete not working for a component

### ISSUE THREAD

**Issue by PrashantAshok** [marko-js/language-server#22]
### Details

When using `ebay-textbox` and trying to add the properties of it, the autocomplete doesn't work and VSCode logs the following error in the `Marko Language Server` output window. 

```
[Error - 3:44:50 PM] Request textDocument/completion failed.
  Message: Request textDocument/completion failed with message: Cannot read property 'type' of undefined
  Code: -32603 
```

```
<ebay-textbox
  class=input.class
  fluid
  value=input.value/>
```

I can see the `ebay-textbox` has the `marko-tag.json` file https://github.com/eBay/ebayui-core/blob/6.0.0/src/components/ebay-textbox/marko-tag.json

### Expected Behavior

This should mimic e.g. what `ebay-checkbox` does 

<img width="641" alt="Screen Shot 2020-09-02 at 3 50 08 PM" src="https://user-images.githubusercontent.com/5200733/92044942-30247780-ed34-11ea-9b4a-32dfcbdad5ca.png">

**Comment by DylanPiercey** [comment]
Should be fixed now!
