### ISSUE TITLE
Commenting in concise gives error in vs code

### ISSUE THREAD

**Issue by Sebring** [marko-js/language-server#29]
### Details

Commenting in the concise part of code gives error in VS Code v1.52.1

Marko VSCode v0.10.0
VS Code v1.52.1
Win 10

### Steps to Reproduce

_component.marko_
```
div
	p -- paragraph
	//
	// add a comment below this line and vs throws error
	//
	ul -- list
		li -- list item

class {
	onMount() {
		//
		// add a comment here - no errors
		//
		
	}
}
```

### Stack Trace

>[Error - 21:26:31] Request textDocument/completion failed.
  Message: Request textDocument/completion failed with message: Illegal state. Invalid tag name
  Code: -32603

**Comment by DylanPiercey** [comment]
@Sebring I am not seeing this issue myself, it's possible it's related to windows, but that seems strange given the recent changes should not impact that.

I did just do a release of the plugin to better handle errors thrown from the parser (`0.10.1`). Could you check if that version still has the issue for you?

**Comment by Sebring** [comment]
I reconfirmed the error then updated to 0.10.1 (that was quick!) and restarted VS Code. I'm no longer seeing the issue either. Very nice.

Most likely unrelated but anyhow, VS Code also installed an update to version 1.53 as i restarted.

Anyhow, thanks. From my POW this issue can be closed.

**Comment by DylanPiercey** [comment]
Awesome, thanks for confirming!
