### ISSUE TITLE
Blank lines before </body> and </head>?

### ISSUE THREAD

**Issue by tusamni** [marko-js/language-server#32]
### Details

On a clean install of Marko basic, I ran the Marko VSCode plugin and I'm getting some unexpected spacing after certain tags.

### Expected Behavior

I'd assume that there wouldn't be blank returns before the </body>, </head> tags.

### Actual Behavior

![image](https://user-images.githubusercontent.com/9271145/118049149-eec47d00-b342-11eb-944e-8cea156d9d9d.png)

### Your Environment

- VS Code Insiders 1.57.0-insider
- Windows 10 build 21H1
- Link to your project: 

### Steps to Reproduce

1. npx @marko/create
2. Run the basic build
3. Install Marko VSCode plugin 
4. Open the app-layout.marko file and run the formatter

**Comment by DylanPiercey** [comment]
We've switched to our new prettier based formatter which should no longer have this issue. http://github.com/marko-js/prettier
