### ISSUE TITLE
VSCode extension converts concise syntax to HTML

### ISSUE THREAD

**Issue by treeder** [marko-js/language-server#33]
### Details

With this extension installed, it automatically converts my `concise` code into html which I do not want. 

### Expected Behavior

Don't convert the code. 

### Actual Behavior

Converts to HTML. 

### Steps to Reproduce

Create a component with concise code and save it.

**Comment by DylanPiercey** [comment]
Under the hood the plugin is using `@marko/prettyprint` which currently doesn't support concise mode detection.

You can however add a `.marko-prettyprint` config file with the `syntax` set to concise: https://github.com/marko-js/cli/blob/main/packages/prettyprint/README.md#marko-prettyprint-config-file

**Comment by DylanPiercey** [comment]
Eventually we plan to replace `@marko/prettyprint` with something more robust and I'll keep this issue in mind.

**Comment by treeder** [comment]
Tried the .marko-prettyprint config, but now I have the opposite problem, it converts all my html components into concise. I'll wait for the replacement.

**Comment by DylanPiercey** [comment]
Since this now uses `@marko/prettyprint` with concise mode detection this shouldn't be an issue!
