### ISSUE TITLE
3 bugs with the tags api

### ISSUE THREAD

**Issue by Nick-Mazuk** [marko-js/language-server#83]
## VS Code

From the VS Code extension `marko-js.marko-vscode` with the version released on `5/13/2022, 15:43:22`.

### Details

When using concise mode, the new tags api, and VS Code, there are three intellesense errors for the following code:

<img width="623" alt="Screen Shot 2022-06-11 at 1 50 41 PM" src="https://user-images.githubusercontent.com/5659171/173204447-114837c8-4c70-43cd-ae03-3a27b5caf3ed.png">

1. Curly braces for codeblocks spanning multiple lines appear invalid (in my color scheme, invalid brackets are colored red). Here, this can be seen in the brackets for `attrs` and `onClick`.
2. Having a default value for an attribute creates the error "Invalid shorthand property initializer".
3. If you remove `greeting = "Hello",` from the above snippet, `let` has the following error: "Unexpected token".

Raw code snippet:

```marko
attrs/{
    greeting = "Hello",
    firstName,
    lastName,
    helloWorld,
    anotherItem,
    ...otherAttrs
}

let/count=0
button onClick() {
    count++
    console.log("hello")
}
    -- ${count}
```

### Expected Behavior

This is all valid syntax for the tags api and therefore should not produce any errors.

<details><summary>Additional Info</summary>

### Your Environment

- Environment name and version: Node v18.1.0
- Operating System and version (desktop or mobile): macOS 12.4.0

Relevant dependencies in package.json:

```json
"@marko/compiler": "^5.21.4",
"@marko/tags-api-preview": "^0.5.3",
"@marko/translator-default": "^5.21.2",
"@marko/vite": "^2.3.2",
"prettier": "^2.6.2",
"prettier-plugin-marko": "^1.2.1",
```

### Steps to Reproduce

1.  Install the VS Code plugin
4.  Create an index.marko file
5.  Copy-paste the above contents into that marko file.
6.  See the errors

</details>

**Comment by DylanPiercey** [comment]
@Nick-Mazuk can you double check what version of htmljs-parser you have installed in the project?
`npm ls htmljs-parser`

Also regarding the brackets it's due to vscode recently changing their default to auto highlight brackets, this plugin needs to be updated to account for that. In the interim you can turn it off: https://code.visualstudio.com/updates/v1_67#_bracket-pair-colorization-enabled-by-default

**Comment by Nick-Mazuk** [comment]
> @Nick-Mazuk can you double check what version of htmljs-parser you have installed in the project?
> `npm ls htmljs-parser`

I'm using htmljs-parser@3.3.6



> Also regarding the brackets it's due to vscode recently changing their default to auto highlight brackets, this plugin needs to be updated to account for that. In the interim you can turn it off: https://code.visualstudio.com/updates/v1_67#_bracket-pair-colorization-enabled-by-default

Sounds good.

**Comment by DylanPiercey** [comment]
FYI the issues should be resolved now, aside from the bracket colorization issue. Work around for that is still to disable that feature.
