### ISSUE TITLE
Definitions returned include empty directories

### ISSUE THREAD

**Issue by rohit-gohri** [marko-js/language-server#9]
### Problem:

When ctrl+clicking a custom component tag in VS Code, the definitions panel shows one extra entry:

- If the component is in the `components` directory alongside the component currently open, it also shows the path of the directory
![Screenshot from 2019-05-12 01-43-14](https://user-images.githubusercontent.com/31949290/57574479-60694800-7457-11e9-8eb0-086f4187678a.png)
- If the component is available through a `marko.json` file, the json file is also shown

The second one could be intentional, so that user is aware which file is making it available, but I think both shouldn't be shown.

### Suggestion:
I did some experiment with a fork some while back and seemed to have fixed it here: https://github.com/rohit-smpx/marko-language-server/commit/f2ff50a22d5bf2cb44d157670f507ca074b8e737, by adding a `fs.stat` and checked if `result.isFile` is true. 

That branch has too many changes. I could open a new PR with just that single change if that looks good?

Also it's great that this got released.

**Comment by DylanPiercey** [comment]
This was fixed at some point but I somehow missed this issue. 😓
